algoritmo "Estrutura de Repetição"

var
i:inteiro

inicio
//Estrutura PARA
Escreval("Estrutura PARA")
para i de 1 ate 5 faca
     escreval(i)
fimpara

// Estrutura ENQUANTO
escreval("")
escreval("")
Escreval("Estrutura ENQUANTO")
i <- 1
enquanto (i <= 5) faca
         escreval (i)
         i <- i + 1
fimenquanto

//Estrutura REPITA
escreval("")
escreval("")
Escreval ("Estrutura REPITA")
i <- 1

repita
      escreval (i)
      i <- i + 1
ate i > 5

fimalgoritmo
